CREATE DATABASE n8n_db;
CREATE DATABASE nextcloud_db;
CREATE DATABASE odoo_db;

CREATE USER n8n_app WITH PASSWORD 'N8N_DB_PASSWORD';
CREATE USER nextcloud_app WITH PASSWORD 'NEXTCLOUD_DB_PASSWORD';
CREATE USER odoo_app WITH PASSWORD 'ODOO_DB_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE n8n_db TO n8n_app;
GRANT ALL PRIVILEGES ON DATABASE nextcloud_db TO nextcloud_app;
GRANT ALL PRIVILEGES ON DATABASE odoo_db TO odoo_app;
